export const FEEL_THE_FORCE = 'FEEL_THE_FORCE';
export const GET_THE_FORCE = 'GET_THE_FORCE';
export const GET_THE_FORCE_SUCCESS = 'GET_THE_FORCE_SUCCESS';
export const GET_THE_FORCE_FAIL = 'GET_THE_FORCE_FAIL';
